version: '2'
volumes:
    influxdbiotwind:

services:
    influxdb:
        image: library/influxdb
        restart: always
        container_name: influxdbiotwind
        ports:
            - "28086:8086"
        volumes:
            - influxdbiotwind:/var/lib/influxdb

        environment:
            - INFLUXDB_DB=iotwind
            # Automatically initializes a database with the name of this environment variable.
#            - INFLUXDB_HTTP_AUTH_ENABLED=true
#            - INFLUXDB_ADMIN_USER=influxadmin
#            - INFLUXDB_ADMIN_PASSWORD=
#            - INFLUXDB_USER=ifxusr
#            - INFLUXDB_USER_PASSWORD=
#            - INFLUXDB_READ_USER=INFLUXDB_USER=iflxusrr
#            - INFLUXDB_READ_USER_PASSWORD=
#            - INFLUXDB_WRITE_USER=ifxusrw
#            - INFLUXDB_WRITE_USER_PASSWORD=
    chronograf:
        image: chronograf
        restart: always
        container_name: chronografiotwind
        ports: 
            - "28888:8888"
    grafana:
        # may need a fixed version, otherwise it is current master branch
        image: grafana/grafana
        restart: always
        container_name: grafanaiotwind
        ports:
            - "28080:3000"
    mosquitto:
        image: eclipse-mosquitto
        container_name: mosquittoiotwind
        restart: always
        ports:
            - "21883:1883"
            - "29001:9001"

